### ISSUE TITLE
Investigate support for IFC file format

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicVR.js#81]
Investigate adding support for the IFC file format:

* The IFC represents a data model structure for sharing construction and facility management data across various applications used in the building domain.
* The IFC data model is an object-oriented data model based on class definitions representing the things (elements, processes, shapes, etc.) that are used by software applications during a construction or facility management project.
* The IFC data model focusses on those classes that are needed to share information (rather then processing it in a particular proprietory software).
* The IFC data model is a neutral and open specification that is not controlled by a singular vendor or group of vendors. 

Examples:

http://www.ifcwiki.org/index.php/Examples

**Comment by cjcliffe** [comment]
Don't think I'll have the opportunity to finish this up as it was just a prototype pass so far with many flaws; the best option in this scenario will be to convert assets to collada so there's a single path for support and maintenance.

**Comment by ssured** [comment]
@cjcliffe: do you have the code of your sprint on IFC parsing somewhere available, maybe I can extend it

**Comment by cjcliffe** [comment]
@ssured I do; it's actually a module in CubicVR.js source already but just not included by default.  You can find an example of it here:

https://github.com/cjcliffe/CubicVR.js/tree/master/samples/ifc

With the relevant line for the IFC module inclusion and sample usage code here:

https://github.com/cjcliffe/CubicVR.js/blob/master/samples/ifc/ifc_experimental.html#L9

```
    <!-- Manual inclusion required until it's out of experimental status. -->
    <script src="../../source/CubicVR.IFC.js" type="text/javascript"></script>
```

Cheers!

**Comment by ssured** [comment]
Thanks for your quick reply and the pointers into the code!
